from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path


PROJECT_ROOT = Path(
    os.path.dirname(
        os.path.dirname(
            os.path.abspath(__file__)
        )
    )
)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT)
    )


from database.job_database import JobDatabase
from matching.job_matcher import match_job


# ============================================================
# CONFIG
# ============================================================

SEARCH_RESULTS_FILE = (
    PROJECT_ROOT
    / "data"
    / "search_results.json"
)

MATCH_CATEGORIES = {
    "STRONG",
    "GOOD",
}

MIN_MATCH_SCORE = 75


# ============================================================
# HELPERS
# ============================================================

def value(
    row,
    *names,
):
    """
    Safely retrieve a database value.
    """

    for name in names:

        try:

            if name not in row.keys():
                continue

            result = row[name]

            if result is not None:
                return str(result)

        except Exception:
            continue

    return ""


def clean_text(
    value_to_clean,
) -> str:

    if value_to_clean is None:
        return ""

    return str(
        value_to_clean
    ).strip()


def make_fingerprint(
    title: str,
    url: str,
    company: str = "",
) -> str:

    raw = "|".join(
        [
            clean_text(company).lower(),
            clean_text(title).lower(),
            clean_text(url).lower(),
        ]
    )

    return hashlib.sha256(
        raw.encode("utf-8")
    ).hexdigest()


# ============================================================
# SEARCH RESULT IMPORT
# ============================================================

def load_search_results() -> list[dict]:
    """
    Load web-search results generated by
    search_collector.py.
    """

    if not SEARCH_RESULTS_FILE.exists():

        print(
            "WEB SEARCH IMPORT"
        )

        print(
            "Search result file not found:"
        )

        print(
            f"  {SEARCH_RESULTS_FILE}"
        )

        print(
            "Continuing with database jobs only."
        )

        return []

    try:

        data = json.loads(
            SEARCH_RESULTS_FILE.read_text(
                encoding="utf-8"
            )
        )

    except Exception as exc:

        print(
            "WARNING: Could not read "
            f"search_results.json: {exc}"
        )

        return []

    if isinstance(
        data,
        dict,
    ):

        results = data.get(
            "results",
            [],
        )

    elif isinstance(
        data,
        list,
    ):

        results = data

    else:

        results = []

    if not isinstance(
        results,
        list,
    ):

        return []

    return [
        item
        for item in results
        if isinstance(item, dict)
    ]


# ============================================================
# IMPORT WEB RESULTS INTO DATABASE
# ============================================================

def import_search_results(
    db: JobDatabase,
) -> tuple[int, int, int]:

    results = load_search_results()

    if not results:

        print()
        print(
            "WEB SEARCH RESULTS: 0"
        )

        return (
            0,
            0,
            0,
        )

    imported = 0
    skipped = 0
    errors = 0

    print()
    print("=" * 90)
    print(
        "IMPORTING PUBLIC WEB SEARCH RESULTS"
    )
    print("=" * 90)

    # Determine which optional columns exist.
    columns = set()

    try:

        column_rows = db.connection.execute(
            "PRAGMA table_info(jobs)"
        ).fetchall()

        for row in column_rows:

            try:
                columns.add(
                    row["name"]
                )
            except Exception:

                try:
                    columns.add(
                        row[1]
                    )
                except Exception:
                    pass

    except Exception as exc:

        print(
            f"WARNING: Could not inspect "
            f"jobs schema: {exc}"
        )

    for index, result in enumerate(
        results,
        start=1,
    ):

        try:

            title = clean_text(
                result.get("title")
            )

            url = clean_text(
                result.get("url")
            )

            snippet = clean_text(
                result.get("snippet")
            )

            result_domain = clean_text(
                result.get("domain")
            )

            source = clean_text(
                result.get("engine")
                or result.get("source")
            )

            if not title or not url:

                skipped += 1
                continue

            # Search-result jobs do not necessarily expose
            # company/location/experience separately.
            #
            # Those fields can be enriched later during
            # verification.

            company = ""

            location = ""

            experience = ""

            description = snippet

            fingerprint = make_fingerprint(
                title,
                url,
                company,
            )

            # ------------------------------------------------
            # DUPLICATE CHECK
            # ------------------------------------------------

            existing = None

            # Prefer fingerprint if the jobs table has it.

            if "fingerprint" in columns:

                existing = db.connection.execute(
                    """
                    SELECT id
                    FROM jobs
                    WHERE fingerprint = ?
                    LIMIT 1
                    """,
                    (
                        fingerprint,
                    ),
                ).fetchone()

            # Fallback to application URL.

            if existing is None:

                url_columns = []

                if "application_url" in columns:
                    url_columns.append(
                        "application_url"
                    )

                if "url" in columns:
                    url_columns.append(
                        "url"
                    )

                for column in url_columns:

                    existing = db.connection.execute(
                        f"""
                        SELECT id
                        FROM jobs
                        WHERE {column} = ?
                        LIMIT 1
                        """,
                        (
                            url,
                        ),
                    ).fetchone()

                    if existing is not None:
                        break

            if existing is not None:

                skipped += 1
                continue

            # ------------------------------------------------
            # BUILD INSERT
            # ------------------------------------------------

            insert_columns = []
            insert_values = []

            def add_column(
                column: str,
                value_to_add,
            ) -> None:

                if column in columns:

                    insert_columns.append(
                        column
                    )

                    insert_values.append(
                        value_to_add
                    )

            add_column(
                "title",
                title,
            )

            add_column(
                "company",
                company,
            )

            add_column(
                "location",
                location,
            )

            add_column(
                "description",
                description,
            )

            add_column(
                "experience_text",
                experience,
            )

            add_column(
                "url",
                url,
            )

            add_column(
                "application_url",
                url,
            )

            add_column(
                "source",
                source or "web_search",
            )

            add_column(
                "fingerprint",
                fingerprint,
            )

            add_column(
                "status",
                "ACTIVE",
            )

            add_column(
                "verification_status",
                "UNVERIFIED",
            )

            add_column(
                "match_score",
                0,
            )

            if not insert_columns:

                errors += 1

                print(
                    "WARNING: jobs table has "
                    "no recognized insert columns."
                )

                continue

            placeholders = ", ".join(
                ["?"] * len(
                    insert_columns
                )
            )

            sql = (
                "INSERT INTO jobs ("
                + ", ".join(
                    insert_columns
                )
                + ") VALUES ("
                + placeholders
                + ")"
            )

            db.connection.execute(
                sql,
                tuple(
                    insert_values
                ),
            )

            imported += 1

        except Exception as exc:

            errors += 1

            print(
                f"WARNING: Web result "
                f"{index} import failed: "
                f"{exc}"
            )

        if index % 100 == 0:

            db.connection.commit()

            print(
                f"Imported: {imported:,} | "
                f"Skipped: {skipped:,} | "
                f"Errors: {errors:,}"
            )

    db.connection.commit()

    print()
    print(
        f"Web results loaded : {len(results):,}"
    )

    print(
        f"Imported            : {imported:,}"
    )

    print(
        f"Skipped             : {skipped:,}"
    )

    print(
        f"Errors              : {errors:,}"
    )

    print("=" * 90)

    return (
        imported,
        skipped,
        errors,
    )


# ============================================================
# MATCHING
# ============================================================

def main() -> None:

    db = JobDatabase()

    # --------------------------------------------------------
    # 1. IMPORT PUBLIC WEB RESULTS
    # --------------------------------------------------------

    import_search_results(
        db
    )

    # --------------------------------------------------------
    # 2. LOAD DATABASE JOBS
    # --------------------------------------------------------

    rows = db.connection.execute(
        """
        SELECT *
        FROM jobs
        ORDER BY rowid DESC
        """
    ).fetchall()

    print("=" * 90)

    print(
        "JOB INTELLIGENCE AGENT"
    )

    print(
        "TECHNICAL FRESHER DATABASE "
        "CLASSIFICATION WORKER"
    )

    print("=" * 90)

    print(
        f"Jobs available: "
        f"{len(rows):,}"
    )

    print()

    # --------------------------------------------------------
    # COUNTERS
    # --------------------------------------------------------

    matched_count = 0
    not_matched_count = 0
    skipped_verified = 0
    skipped_alerted = 0
    skipped_no_title = 0

    matched_jobs = []

    # --------------------------------------------------------
    # PROCESS JOBS
    # --------------------------------------------------------

    for index, job in enumerate(
        rows,
        start=1,
    ):

        job_id = job["id"]

        title = value(
            job,
            "title",
        )

        company = value(
            job,
            "company",
        )

        location = value(
            job,
            "location",
        )

        experience = value(
            job,
            "experience_text",
            "experienceText",
            "experience",
        )

        description = value(
            job,
            "description",
        )

        current_status = value(
            job,
            "status",
        ).upper()

        # ----------------------------------------------------
        # PRESERVE VERIFIED / ALERTED
        # ----------------------------------------------------

        if current_status == "VERIFIED":

            skipped_verified += 1
            continue

        if current_status == "ALERTED":

            skipped_alerted += 1
            continue

        # ----------------------------------------------------
        # MISSING TITLE
        # ----------------------------------------------------

        if not title:

            skipped_no_title += 1

            db.connection.execute(
                """
                UPDATE jobs
                SET status = ?,
                    updated_at =
                        CURRENT_TIMESTAMP
                WHERE id = ?
                """,
                (
                    "NOT_MATCHED",
                    job_id,
                ),
            )

            not_matched_count += 1

            continue

        # ----------------------------------------------------
        # MATCH
        # ----------------------------------------------------

        result = match_job(
            title=title,
            description=description,
            location=location,
            experience_text=experience,
        )

        category = str(
            result.get(
                "category",
                "NONE",
            )
        ).upper()

        score = int(
            result.get(
                "match_score",
                0,
            )
            or 0
        )

        india_eligible = bool(
            result.get(
                "india_eligible",
                False,
            )
        )

        is_match = (
            category
            in MATCH_CATEGORIES
            and india_eligible
            and score >= MIN_MATCH_SCORE
        )

        # ----------------------------------------------------
        # MATCHED
        # ----------------------------------------------------

        if is_match:

            matched_count += 1

            matched_jobs.append(
                (
                    job_id,
                    title,
                    company,
                    location,
                    score,
                    category,
                )
            )

            db.connection.execute(
                """
                UPDATE jobs
                SET status = 'ACTIVE',
                    verification_status =
                        CASE
                            WHEN verification_status =
                                'VERIFIED'
                            THEN verification_status
                            ELSE 'UNVERIFIED'
                        END,
                    match_score = ?,
                    updated_at =
                        CURRENT_TIMESTAMP
                WHERE id = ?
                """,
                (
                    score,
                    job_id,
                ),
            )

        # ----------------------------------------------------
        # NOT MATCHED
        # ----------------------------------------------------

        else:

            not_matched_count += 1

            db.connection.execute(
                """
                UPDATE jobs
                SET status = 'NOT_MATCHED',
                    match_score = ?,
                    updated_at =
                        CURRENT_TIMESTAMP
                WHERE id = ?
                """,
                (
                    score,
                    job_id,
                ),
            )

        # ----------------------------------------------------
        # PERIODIC COMMIT
        # ----------------------------------------------------

        if index % 1000 == 0:

            db.connection.commit()

            print(
                f"Processed: "
                f"{index:,}/"
                f"{len(rows):,} | "
                f"Matched: "
                f"{matched_count:,} | "
                f"Not matched: "
                f"{not_matched_count:,}"
            )

    db.connection.commit()

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print()

    print("=" * 90)

    print(
        "CLASSIFICATION COMPLETE"
    )

    print("=" * 90)

    print(
        f"Jobs scanned       : "
        f"{len(rows):,}"
    )

    print(
        f"Technical matches  : "
        f"{matched_count:,}"
    )

    print(
        f"Not matched        : "
        f"{not_matched_count:,}"
    )

    print(
        f"Already VERIFIED   : "
        f"{skipped_verified:,}"
    )

    print(
        f"Already ALERTED    : "
        f"{skipped_alerted:,}"
    )

    print(
        f"No title           : "
        f"{skipped_no_title:,}"
    )

    print()

    print(
        "-" * 90
    )

    print(
        "TOP MATCHES"
    )

    print(
        "-" * 90
    )

    matched_jobs.sort(
        key=lambda item: item[4],
        reverse=True,
    )

    for (
        job_id,
        title,
        company,
        location,
        score,
        category,
    ) in matched_jobs[:50]:

        print(
            f"{score:3}/100 | "
            f"{category:8} | "
            f"ID {job_id:<7} | "
            f"{title[:45]:45} | "
            f"{company[:25]:25} | "
            f"{location[:30]}"
        )

    print(
        "-" * 90
    )

    print()

    print(
        "Database status:"
    )

    print(
        "  MATCH      → ACTIVE + UNVERIFIED"
    )

    print(
        "  NO MATCH   → NOT_MATCHED"
    )

    print(
        "  VERIFIED   → preserved"
    )

    print(
        "  ALERTED    → preserved"
    )

    print()

    print(
        "No jobs were physically deleted."
    )

    print(
        "=" * 90
    )


if __name__ == "__main__":
    main()
